-- Create profiles table for user profile data matching the exact Supabase schema
CREATE TABLE IF NOT EXISTS public.profiles (
  id bigint generated by default as identity not null,
  name text null,
  photo_url text null,
  created_at timestamp with time zone not null default now(),
  icon text null,
  constraint username_pkey primary key (id)
) TABLESPACE pg_default;

-- Disable RLS explicitly as requested
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
