CREATE TABLE IF NOT EXISTS public.statuses (
  status_id bigint generated by default as identity not null,
  status text null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  constraint statuses_pkey primary key (status_id),
  constraint statuses_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;

ALTER TABLE public.statuses DISABLE ROW LEVEL SECURITY;
