CREATE TABLE IF NOT EXISTS public.comments (
  comment_id bigint generated by default as identity not null,
  status_id bigint null,
  user_id bigint null,
  comment text null,
  created_at timestamp with time zone not null default now(),
  constraint comments_pkey primary key (comment_id),
  constraint comments_status_id_fkey foreign KEY (status_id) references statuses (status_id),
  constraint comments_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;

ALTER TABLE public.comments DISABLE ROW LEVEL SECURITY;
